### ISSUE TITLE
Examples of user requests from skit client to skit server

### ISSUE THREAD

**Issue by AmitKumarDas** [clusterinc/skit#12]
Can I get the flow or code snippet that showcases a user action event which leads to a GET/POST etc call from the skit Controller's client function to skit Controller's server function and then renders back at the client side.

**Comment by taylorhughes** [comment]
Working on a todomvc implementation ( #6 ) that will show state-altering behavior — look for that sometime in the next week.

**Comment by taylorhughes** [comment]
Here's an example: https://github.com/taylorhughes/skit-todomvc
