### ISSUE TITLE
Skit integrated in Meteor.js?

### ISSUE THREAD

**Issue by alitavector** [clusterinc/skit#2]
Found your link (https://medium.com/on-coding/oh-god-i-built-another-javascript-framework-fb32f0f8ec12) from HackerNews, sound like skit could be really really useful to integrated into Meteor with more ways to render contents with pure API clients or backend UI, don't you think? I love polymer but it was too complicated to get things done like you did and your approach in Skit could solve some of the use case in Meteor e.g. CSS in package.

MDG is active at https://forums.meteor.com

**Comment by taylorhughes** [comment]
Not looking to get any other frameworks integrated into skit at this time. But if there were any small changes to make the framework/runtime work better with things like meteor I'd definitely entertain more specific bugs or pull requests around how to enable that.
