### ISSUE TITLE
setTimeout in baseController.js

### ISSUE THREAD

**Issue by TheSisb** [clusterinc/skit#5]
Not sure where to ask, hope you don't mind me asking here.

I was browsing through the tutorial and the examples because this framework really appealed to me when I noticed a setTimeout in your baseController here: https://github.com/clusterinc/skit/blob/master/example/skitjs.com/library/BaseController.js

Could you explain why that was necessary? 
Thanks

**Comment by taylorhughes** [comment]
It's not necessary, it's just to ensure that the tracking code loads _after_ anything in the initial response. (Things would be exactly the same if there were no setTimeout, except the browser might prioritize loading that tracking script sooner than something else on the page.)
