### ISSUE TITLE
Error: Invalid dependency: "skit.platform.iter" in module: public.Home:js - in rottentomatoes example

### ISSUE THREAD

**Issue by psaitu** [clusterinc/skit#9]
Hi, i have this issue with the rottentomatoes example. The skit-react example works perfectly, but i have a dependency error on this one.

**Comment by taylorhughes** [comment]
Thanks for the bug report!

Just pushed a change to update package.json to reference modern skit; it was pointing to a very old version of skit. If you pull from master it should be up to date. (If you're using the npm package, you'll need to just run `npm install skit@0.1.2` in the rottentomatoes dir to update it manually.)
